# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/pct/',
                'doc_host': 'https://perceptualrobots.github.io',
                'git_url': 'https://github.com/perceptualrobots/pct/tree/master/',
                'lib_path': 'pct'},
  'syms': { 'pct.architectures': {},
            'pct.environments': {},
            'pct.errors': {},
            'pct.functions': {},
            'pct.hierarchy': {},
            'pct.nodes': {},
            'pct.plotting': {},
            'pct.putils': {},
            'pct.structure': {}}}
