# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_configurations.ipynb (unless otherwise specified).

__all__ = ['BaseConfiguration']

# Cell
import gym
import random
import os

from abc import ABC, abstractmethod

# Cell
class BaseConfiguration(ABC):
    "Base class of an array configuration. This class is not used direclty by developers, but defines the functionality common to all."
    def __init__(self, name, num_inputs, num_actions, grid, references):
        self.name = name
        self.num_inputs=num_inputs
        self.num_actions=num_actions
        self.grid=grid
        self.references=references
        self.config={}

    def create_config(self):
        level0 = self.level0config()

