# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_functions.ipynb (unless otherwise specified).

__all__ = ['BaseFunction']

# Cell
class BaseFunction(ABC):
    "Base class of a PCT function."
    def __init__(self):
        self.output = 0

    @abstractmethod
    def get_output(self):
        pass